### PR TITLE
Add an example of extending MIDDLEWARE_CLASSES

### PR DESCRIPTION
**Pull request by ptim**
Hey Curtis - I didn't find this documented..

Not sure that the rst is well formatted - contains a weird mix of 3 and 4 spaces.. maybe that's normal?! I just copied the convention in the file..

Lemme know if it's helpful, or you'd like it tweaked..

### CODE REVIEW

**Comment by funkybob** [comment]
So it conditionally adds the middleware if it can import it?  Seems exceedingly fragile...

**Comment by funkybob** [comment]
Why not just extend it directly, and let errors raise when you run it so they're not hidden?

**Comment by rapilabs** [comment]
It's not very explicit :P

**Comment by funkybob** [comment]
I'm not clear on the value of this addition... closing for now.

**Pull request closed without merging**
