### PR TITLE
add support for .env files

### PR DESCRIPTION
**Pull request by amirreza8002**
closes#47

i have made these changes:

1- added django-environ as an optional dependency
you could either make it a required dependency
or make the methods more abstract so users can use whatever parsing tool they want.

2- add one optional parameter to use() and get_settings_instance() methods
if the user provides a path, it will be used
othersie it defaluts to None and methods go as they did before
if a file path is given but the file doesn't exist, fallback to `os.environ`. (useful for ci/cd when .env file isn't available)
also some safty check just in case, and some docstrings

3- added .idea to .gitignore for pycharm

let me know if you have any thoughts on this

### CODE REVIEW

**Comment by funkybob** [comment]
This appears to be branched not from master?

**Comment by amirreza8002** [comment]
i forked the master
but i used reset once cause i was going wrong
maybe that has made it look confusing
but as you can see in the commits it uses the last commit from the master branch

**Comment by amirreza8002** [comment]
@funkybob hi
sorry for pinging
but should i proceed?

**Comment by funkybob** [comment]
The diff still shows changes from a branch I've not merged yet.

**Comment by amirreza8002** [comment]
that's... strange
it shows me that i forked the master branch
i'll look into it

**Pull request closed without merging**
